name: rsg4
dependencies:
  - tensorflow=1.15.0
  - jupyter=1.0.0
  - pip
  - pandas=1.1.3
  - scikit-image=0.17.2
  - numba=0.51.2
  - pip:
    - n2v==0.1.11
    - napari==0.3.8
    - tifffile==2020.6.3
    - cupy-cuda102-8.1.0
